[tool.poetry]
name = "docs.peeringdb.com"
version = "1.0.0"
description = "PeeringDB Documentation site"
authors = ["Outreach Committee <outreachcom@lists.peeringdb.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
# docs
# Need Jinja <3.1 until https://github.com/mkdocs/mkdocs/issues/2794 is released
jinja2 = "^3,<3.1"
markdown = "*"
markdown-include = ">=0.5,<1"
mkdocs = "^1.2.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
